services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/rust.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:9.4.0
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-api_user}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=${DATABASE:-api_db}
    volumes:
      - ./database/mysql:/var/lib/mysql
